# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_short',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
